from batcore.data import StandardDataset, RevFinderDataset, RevRecDataset, TieDataset, PullLoader

model_setup = {
    'ACRec': {'item2id': False,
              'model_kwargs': {},
              'dataset': 'standard',
              'dataset_kwargs': {'comments': True},
              'iterator': 'full',
              'iterator_kwargs': {}},
    'cHRev': {'item2id': False,
              'model_kwargs': {},
              'dataset': 'standard',
              'dataset_kwargs': {'comments': True},
              'iterator': 'full',
              'iterator_kwargs': {}},
    'CN': {'item2id': True,
           'model_kwargs': {},
           'dataset': 'standard',
           'dataset_kwargs': {'comments': True, 'user_items': True},
           'iterator': 'full',
           'iterator_kwargs': {}},
    'RevFinder': {'item2id': True,
                  'model_kwargs': {},
                  'dataset': 'revfinder',
                  'dataset_kwargs': {},
                  'iterator': 'batch',
                  'iterator_kwargs': {'batch_size': 5}},
    'RevRec': {'item2id': True,
               'model_kwargs': {},
               'dataset': 'revrec',
               'dataset_kwargs': {'comments': True, 'user_items': True},
               'iterator': 'batch',
               'iterator_kwargs': {'batch_size': 5}},
    'Tie': {'item2id': True,
            'model_kwargs': {},
            'dataset': 'tie',
            'dataset_kwargs': {},
            'iterator': 'full',
            'iterator_kwargs': {}},
    'WRC': {'item2id': True,
            'model_kwargs': {},
            'dataset': 'standard',
            'dataset_kwargs': {'user_items': True, 'file_items': True},
            'iterator': 'batch',
            'iterator_kwargs': {'batch_size': 50}},
    'xFinder': {'item2id': False,
                'model_kwargs': {},
                'dataset': 'standard',
                'dataset_kwargs': {'commits': True},
                'iterator': 'full',
                'iterator_kwargs': {}},

}

dataset_classes = {'standard': StandardDataset,
                   'tie': TieDataset,
                   'revfinder': RevFinderDataset,
                   'revrec': RevRecDataset}

iterator_classes = {'batch': PullLoader,
                    'full': PullLoader}
